# -*- coding: utf-8 -*-
"""inventory_and_scenario_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4knn7LS3H6-g4eptbptpsjF8sWL7Xw2
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/olist_supply_chain_cleaned.csv')
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

print("data loaded successfully")
print("Shape:", df.shape)
df.head()

# create order date
df['order_date'] = df['order_purchase_timestamp'].dt.date

# daily demand by category
daily_demand = df.groupby(['product_category_name_english', 'order_date']).size().reset_index(name='daily_orders')

# category level stats
category_stats = daily_demand.groupby('product_category_name_english').agg(
    avg_daily_demand = ('daily_orders', 'mean'),
    std_daily_demand = ('daily_orders', 'std'),
    total_orders = ('daily_orders', 'sum')
).reset_index()

# avg. lead time by category
lead_time_stats = df.groupby('product_category_name_english')['lead_time'].mean().reset_index()
lead_time_stats.columns = ['product_category_name_english', 'avg_lead_time']

# merged
inventory_df = category_stats.merge(lead_time_stats, on='product_category_name_english')

print(inventory_df.head(10))

# z-score for 95% service level ≈ 1.65
z= 1.65

inventory_df['safety_stock'] = z * inventory_df['std_daily_demand'] * np.sqrt(inventory_df['avg_lead_time'])

# round values
inventory_df['safety_stock'] = inventory_df['safety_stock'].round(1)
inventory_df['avg_daily_demand'] = inventory_df['avg_daily_demand'].round(2)
inventory_df['avg_lead_time'] = inventory_df['avg_lead_time'].round(1)

# sorted by highest safety stock
inventory_df = inventory_df.sort_values('safety_stock', ascending=False)

print(inventory_df.head(15))

inventory_df.to_csv('category_inventory_analysis.csv', index=False)
print("File saved: category_inventory_analysis.csv")



# seller performance
seller_perf = df.groupby('seller_state').agg(
    total_orders = ('order_id', 'count'),
    delayed_orders = ('is_delayed', 'sum'),
    avg_lead_time = ('lead_time', 'mean'),
    avg_delay = ('delivery_delay', 'mean')
).reset_index()

seller_perf['delay_rate'] = (seller_perf['delayed_orders'] / seller_perf['total_orders'] * 100).round(2)
seller_perf = seller_perf.sort_values('delay_rate', ascending=False)

print("Worst performing seller states:")
print(seller_perf.head(10))

# scenario a - remove worst 10% sellers
threshold = seller_perf['delay_rate'].quantile(0.90)

# sellers to keep (better performing ones)
good_sellers = seller_perf[seller_perf['delay_rate'] < threshold]['seller_state']

df_scenario_a = df[df['seller_state'].isin(good_sellers)]

print("=== Scenario A: Remove Worst 10% Sellers ===")
print("Original On-Time %: {:.2f}%".format((1 - df['is_delayed'].mean()) * 100))
print("New On-Time %: {:.2f}%".format((1 - df_scenario_a['is_delayed'].mean()) * 100))
print("Original Avg Lead Time: {:.2f} days".format(df['lead_time'].mean()))
print("New Avg Lead Time: {:.2f} days".format(df_scenario_a['lead_time'].mean()))

# Find categories with highest average delay
category_delay = df.groupby('product_category_name_english')['delivery_delay'].mean().sort_values(ascending=False)
top_delayed_categories = category_delay.head(5).index.tolist()

print("Top 5 Delayed Categories:")
print(top_delayed_categories)
print("\nAverage Delay of these categories:")
print(category_delay.head(5))

# scenario b - reduce lead time of top delayed categories by 20%
df_scenario_b = df.copy()
mask = df_scenario_b['product_category_name_english'].isin(top_delayed_categories)
df_scenario_b.loc[mask, 'lead_time'] = df_scenario_b.loc[mask, 'lead_time'] * 0.80

print("\n=== Scenario B: Reduce Lead Time of Top 5 Delayed Categories by 20% ===")
print("Original Avg Lead Time: {:.2f} days".format(df['lead_time'].mean()))
print("New Avg Lead Time: {:.2f} days".format(df_scenario_b['lead_time'].mean()))
print("Original On-Time %: {:.2f}%".format((1 - df['is_delayed'].mean()) * 100))
print("New On-Time %: {:.2f}%".format((1 - df_scenario_b['is_delayed'].mean()) * 100))



# categories with highest delay rate
category_delay_rate = df.groupby('product_category_name_english').agg(
    total_orders = ('order_id', 'count'),
    delayed_orders = ('is_delayed', 'sum'),
    avg_lead_time = ('lead_time', 'mean'),
    total_revenue = ('total_value', 'sum')
).reset_index()

category_delay_rate['delay_rate'] = (category_delay_rate['delayed_orders'] / category_delay_rate['total_orders'] * 100).round(2)
category_delay_rate = category_delay_rate.sort_values('delay_rate', ascending=False)

print("=== Categories with Highest Delay Rate ===")
print(category_delay_rate.head(10))

# high volume + high delay categories
high_impact = category_delay_rate[category_delay_rate['total_orders'] > 500].sort_values(['delay_rate', 'total_revenue'], ascending=[False, False])
print("\n=== High Volume Categories with Delay Problems ===")
print(high_impact.head(8))